add business type extractor
usc-isi-i2/dig-business-type-extractor pull request #1
Opened 2016-10-07 08:27 UTC by ZwEin27

2016-10-07 16:45 UTC, jasonslepicka requested changes
We need to refactor the WEDC and BusinessTypeExtractor so we aren't building and training the model on every call to predict.

2016-10-07 16:45 UTC, jasonslepicka commented on digBusinessTypeExtractor/documentation_classification.py
> +    def __init__(self, data_path=os.path.join(DATA_DIR, 'dataset.csv'), vectorizer_type='count', classifier_type='knn'):
There some serious problems with this approach.  If we have to load the dataset and train it every time we run the program it's going to be really slow to start up.  We also need to update setup.py to including the training resources. If we're loading it and training it every time we call predict, it's going to be even slower.  We should allow users to pass in a WEDC in the BusinessTypeExtractor.  We should also add a method to the WEDC utility to let users serialize their trained classifers. 

Predict should just include
```
vectors = self.vectorizer.fit_transform(test_data_corpus).toarray()
test_X = vectors
pred_y = self.classifier.predict(test_X)
pred_y = [DC_CATEGORY_NAMES[int(i)] for i in pred_y]
return pred_y
```

2016-10-07 20:39 UTC, ZwEin27 commented on digBusinessTypeExtractor/documentation_classification.py
> +    def __init__(self, data_path=os.path.join(DATA_DIR, 'dataset.csv'), vectorizer_type='count', classifier_type='knn'):
Hi Jason, thanks for pointing out, :). I have updated it, and please have a look for the detail, thank you

2016-10-13 01:12 UTC, jasonslepicka requested changes
Still need some more changes.  Sorry :/

2016-10-13 01:12 UTC, jasonslepicka commented on digBusinessTypeExtractor/documentation_classification.py
> +            vectorizer = joblib.load(vectorizer_model_path)
It looks like you're loading the classifier and vectorizer every time you call predict.  You should test to see if classifier and vectorizer are None before loading them again.

2016-10-13 01:12 UTC, jasonslepicka commented on digBusinessTypeExtractor/documentation_classification.py
> +            # content = ' '.join([_ for _ in content.split() if _ not in STOP_WORDS])
It looks like you aren't removing stop words.  It looks like we can use "english" or just pass STOP_WORDS to TfIdfVectorizer (you might have to convert it to a list first though).  http://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.TfidfVectorizer.html

2016-10-13 01:12 UTC, jasonslepicka commented on digBusinessTypeExtractor/documentation_classification.py
> +        joblib.dump(self.classifier, self.classifier_model_path)
I don't think you should write the model out by default.  This should be another method that the user should be able to call after training.

2016-10-13 01:12 UTC, jasonslepicka commented on digBusinessTypeExtractor/documentation_classification.py
> +            vectorizer = joblib.load(vectorizer_model_path)
Why aren't you using the self.classifier and self.vectorizer?

2016-10-13 01:12 UTC, jasonslepicka commented on digBusinessTypeExtractor/documentation_classification.py
> +APP_DIR = os.path.join(USER_HOME_PATH, 'WEDC_DATA')
I don't think it's a good idea to create a default directory, especially not in the user's home.  You may not always have access to it.  When we're running on the cluster, some users don't even have a home directory.  The user should always specify where it is or at least make it an environment variable so we can override it.  I don't think having init_env() is a good idea.  if we're going to ship the package with the data, we might as well include a default tfidf/cosine model in the package as well, so we don't have to train the model everytime we run the program on a new machine.

2016-10-19 23:54 UTC, ZwEin27 commented on digBusinessTypeExtractor/documentation_classification.py
> +            # content = ' '.join([_ for _ in content.split() if _ not in STOP_WORDS])
done for stopwords

2016-10-19 23:58 UTC, ZwEin27 commented on digBusinessTypeExtractor/documentation_classification.py
> +        joblib.dump(self.classifier, self.classifier_model_path)
updated logic to save model

2016-10-20 00:38 UTC, ZwEin27 commented on digBusinessTypeExtractor/documentation_classification.py
> +            vectorizer = joblib.load(vectorizer_model_path)
update logic for self.classifier and self.vectorizer

2016-10-20 01:25 UTC, jasonslepicka approved these changes

2016-10-20 01:25 UTC, merged